name: pr preview

on:
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install dependencies & build
        env:
          PATH_PREFIX: "/gate.directory/pr-preview/pr-${{ github.event.number }}/"
        run: |
          npm ci
          npm run build
      - name: Publish preview
        uses: rossjrw/pr-preview-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./_site
